site_name: JVol Rust
site_url: https://fepegar.github.io/jvol-rust/
site_description: >-
  Lightning-fast JPEG-like compression for 3D medical images, written in Rust.

repo_name: fepegar/jvol-rust
repo_url: https://github.com/fepegar/jvol-rust

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.sections
    - navigation.top
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fepegar/jvol-rust

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli.md
  - Algorithm: algorithm.md
  - Benchmark: benchmark.md
